/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.chocolateVendingMachine;

import static my.val.ValidationAndCalculationMethods.*;

/**
 * addStockFrame class providing administrative interface for inventory
 * management. This JFrame allows authorized users to manage both product
 * inventory and coin quantities in the vending machine system.
 *
 * <p>
 * The frame provides increment/decrement controls for:</p>
 * <ul>
 * <li>Chocolate bar stock levels (Twix, KitKat, Mars, Kinder)</li>
 * <li>Coin quantities for all supported denominations</li>
 * <li>Real-time updates to both display and main screen</li>
 * </ul>
 *
 * <p>
 * All changes are immediately reflected in the main screen's static variables
 * and corresponding UI components.</p>
 *
 * @author Tomasz Touma
 * @version 1.0
 * @since 2024
 */
public class addStockFrame extends javax.swing.JFrame {

    /**
     * Creates new form addStockFrame
     */
    public addStockFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTwix = new javax.swing.JLabel();
        jLabelKitkat = new javax.swing.JLabel();
        jLabelMars = new javax.swing.JLabel();
        jLabelKinder = new javax.swing.JLabel();
        jButtonTwixPls = new javax.swing.JButton();
        jButtonTwixMin = new javax.swing.JButton();
        jButtonKitkatMin = new javax.swing.JButton();
        jButtonKitkatpls = new javax.swing.JButton();
        jButtonMarsPls = new javax.swing.JButton();
        jButtonKinderPls = new javax.swing.JButton();
        jButtonMarsMn = new javax.swing.JButton();
        jButtonKinderMin = new javax.swing.JButton();
        jTextFieldTwixAv = new javax.swing.JTextField();
        jTextFieldKitkatAv = new javax.swing.JTextField();
        jTextFieldMarsAv = new javax.swing.JTextField();
        jTextFieldKinderAv = new javax.swing.JTextField();
        jLabelStock = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelFloat = new javax.swing.JLabel();
        jLabel10c = new javax.swing.JLabel();
        jLabel20c = new javax.swing.JLabel();
        jLabel50c = new javax.swing.JLabel();
        jLabel1euro = new javax.swing.JLabel();
        jLabel2euro = new javax.swing.JLabel();
        jTextField10cCoins = new javax.swing.JTextField();
        jTextField20cCoins = new javax.swing.JTextField();
        jTextField50cCoins = new javax.swing.JTextField();
        jTextField1euroCoins = new javax.swing.JTextField();
        jTextField2euroCoins = new javax.swing.JTextField();
        jButton10cMin = new javax.swing.JButton();
        jButton10cPls = new javax.swing.JButton();
        jButton20cMin = new javax.swing.JButton();
        jButton20cPls = new javax.swing.JButton();
        jButton50cMin = new javax.swing.JButton();
        jButton50cPls = new javax.swing.JButton();
        jButton1euroMin = new javax.swing.JButton();
        jButton1euroPls = new javax.swing.JButton();
        jButton2euroMin = new javax.swing.JButton();
        jButton2euroPls = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldMachineMoney = new javax.swing.JTextField();
        jButtonClose = new javax.swing.JButton();
        jTextFieldErrorField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelTwix.setText("Twix");

        jLabelKitkat.setText("KitKat");

        jLabelMars.setText("Mars");

        jLabelKinder.setText("Kinder");

        jButtonTwixPls.setText("+");
        jButtonTwixPls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTwixPlsActionPerformed(evt);
            }
        });

        jButtonTwixMin.setText("-");
        jButtonTwixMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTwixMinActionPerformed(evt);
            }
        });

        jButtonKitkatMin.setText("-");
        jButtonKitkatMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKitkatMinActionPerformed(evt);
            }
        });

        jButtonKitkatpls.setText("+");
        jButtonKitkatpls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKitkatplsActionPerformed(evt);
            }
        });

        jButtonMarsPls.setText("+");
        jButtonMarsPls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMarsPlsActionPerformed(evt);
            }
        });

        jButtonKinderPls.setText("+");
        jButtonKinderPls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKinderPlsActionPerformed(evt);
            }
        });

        jButtonMarsMn.setText("-");
        jButtonMarsMn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMarsMnActionPerformed(evt);
            }
        });

        jButtonKinderMin.setText("-");
        jButtonKinderMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKinderMinActionPerformed(evt);
            }
        });

        jTextFieldTwixAv.setText(Integer.toString(mainScreen.twixAvb));
        jTextFieldTwixAv.setEnabled(false);

        jTextFieldKitkatAv.setText(Integer.toString(mainScreen.kitkatAvb));
        jTextFieldKitkatAv.setEnabled(false);

        jTextFieldMarsAv.setText(Integer.toString(mainScreen.marsAvb));
        jTextFieldMarsAv.setEnabled(false);

        jTextFieldKinderAv.setText(Integer.toString(mainScreen.kinderAvb));
        jTextFieldKinderAv.setEnabled(false);

        jLabelStock.setText("Stock");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMars)
                            .addComponent(jLabelKinder)
                            .addComponent(jLabelTwix, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelKitkat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelStock)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonMarsMn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonKinderMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMarsAv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldKinderAv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonKitkatMin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldKitkatAv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonTwixMin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldTwixAv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonTwixPls, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(jButtonMarsPls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonKitkatpls, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonKinderPls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTwix)
                            .addComponent(jButtonTwixMin)
                            .addComponent(jTextFieldTwixAv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTwixPls)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelStock)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMarsAv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMarsMn)
                            .addComponent(jButtonMarsPls)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelKitkat, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonKitkatMin)
                                .addComponent(jTextFieldKitkatAv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonKitkatpls)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelMars)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKinder, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonKinderMin)
                    .addComponent(jTextFieldKinderAv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonKinderPls))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelFloat.setText("Float");

        jLabel10c.setText("10c");

        jLabel20c.setText("20c");

        jLabel50c.setText("50c");

        jLabel1euro.setText("1€");

        jLabel2euro.setText("2€");

        jTextField10cCoins.setText(Integer.toString(mainScreen.c10Coins));
        jTextField10cCoins.setEnabled(false);

        jTextField20cCoins.setText(Integer.toString(mainScreen.c20Coins));
        jTextField20cCoins.setEnabled(false);

        jTextField50cCoins.setText(Integer.toString(mainScreen.c50Coins));
        jTextField50cCoins.setEnabled(false);

        jTextField1euroCoins.setText(Integer.toString(mainScreen.euro1Coins));
        jTextField1euroCoins.setEnabled(false);

        jTextField2euroCoins.setText(Integer.toString(mainScreen.euro2Coins));
        jTextField2euroCoins.setEnabled(false);

        jButton10cMin.setText("-");
        jButton10cMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10cMinActionPerformed(evt);
            }
        });

        jButton10cPls.setText("+");
        jButton10cPls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10cPlsActionPerformed(evt);
            }
        });

        jButton20cMin.setText("-");
        jButton20cMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20cMinActionPerformed(evt);
            }
        });

        jButton20cPls.setText("+");
        jButton20cPls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20cPlsActionPerformed(evt);
            }
        });

        jButton50cMin.setText("-");
        jButton50cMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50cMinActionPerformed(evt);
            }
        });

        jButton50cPls.setText("+");
        jButton50cPls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50cPlsActionPerformed(evt);
            }
        });

        jButton1euroMin.setText("-");
        jButton1euroMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1euroMinActionPerformed(evt);
            }
        });

        jButton1euroPls.setText("+");
        jButton1euroPls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1euroPlsActionPerformed(evt);
            }
        });

        jButton2euroMin.setText("-");
        jButton2euroMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2euroMinActionPerformed(evt);
            }
        });

        jButton2euroPls.setText("+");
        jButton2euroPls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2euroPlsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel10c)
                        .addComponent(jLabel20c))
                    .addComponent(jLabel1euro)
                    .addComponent(jLabel2euro)
                    .addComponent(jLabel50c))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton10cMin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton20cMin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField10cCoins, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField20cCoins, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1euroMin, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                                    .addComponent(jButton2euroMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1euroCoins, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2euroCoins, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton50cMin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField50cCoins, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabelFloat)
                        .addGap(33, 33, 33)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2euroPls, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jButton1euroPls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton50cPls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton20cPls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10cPls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFloat, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10c)
                    .addComponent(jTextField10cCoins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10cMin)
                    .addComponent(jButton10cPls))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20c)
                    .addComponent(jTextField20cCoins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20cMin)
                    .addComponent(jButton20cPls))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50c)
                    .addComponent(jButton50cMin)
                    .addComponent(jTextField50cCoins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton50cPls))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1euro)
                    .addComponent(jButton1euroMin)
                    .addComponent(jTextField1euroCoins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1euroPls))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2euroCoins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2euro)
                    .addComponent(jButton2euroMin)
                    .addComponent(jButton2euroPls))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel12.setText("Money in the machine:");

        jTextFieldMachineMoney.setText("€"+Double.toString(mainScreen.machineMoney));
        jTextFieldMachineMoney.setEnabled(false);

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jTextFieldErrorField.setDisabledTextColor(new java.awt.Color(255, 0, 51));
        jTextFieldErrorField.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(12, 12, 12)
                        .addComponent(jTextFieldMachineMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldErrorField, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonClose)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldMachineMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClose)
                    .addComponent(jTextFieldErrorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        if (mainScreen.c10Coins<=2){
            jTextFieldErrorField.setText("Please add 10 Cents coins to the machine");

        }else if(mainScreen.c20Coins<=2){
            jTextFieldErrorField.setText("Please add 20 Cents coins to the machine");

        }else if(mainScreen.c50Coins<=2){
            jTextFieldErrorField.setText("Please add 50 Cents coins to the machine");
        }else if(mainScreen.euro1Coins<=2){
            jTextFieldErrorField.setText("Please add 1 euro coins to the machine");
        }else if(mainScreen.euro2Coins<=2){
            jTextFieldErrorField.setText("Please add 2 euro coins to the machine");
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the stock management frame and returns to the main interface.
     * Disposes of the current window without affecting the main application.
     *
     * @param evt The action event triggered by clicking the "Close" button
     */
    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    /**
     * Increases the available quantity of Twix chocolate bars by one unit.
     * Updates both the main screen's static variable and the corresponding text
     * fields in both the main screen and this management interface.
     *
     * @param evt The action event triggered by clicking the "Twix Plus" button
     */
    private void jButtonTwixPlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTwixPlsActionPerformed
        mainScreen.twixAvb++;
        mainScreen.jTextFieldTwixAv.setText(Integer.toString(mainScreen.twixAvb));
        jTextFieldTwixAv.setText(Integer.toString(mainScreen.twixAvb));
    }//GEN-LAST:event_jButtonTwixPlsActionPerformed

    /**
     * Decreases the available quantity of Twix chocolate bars by one unit,
     * ensuring the quantity does not drop below zero. Updates both the main
     * screen's static variable and the corresponding text fields in both
     * interfaces.
     *
     * @param evt The action event triggered by clicking the "Twix Minus" button
     */
    private void jButtonTwixMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTwixMinActionPerformed
        if (mainScreen.twixAvb > 0) {
            mainScreen.twixAvb--;
        }
        mainScreen.jTextFieldTwixAv.setText(Integer.toString(mainScreen.twixAvb));
        jTextFieldTwixAv.setText(Integer.toString(mainScreen.twixAvb));
    }//GEN-LAST:event_jButtonTwixMinActionPerformed

    /**
     * Increases the available quantity of KitKat chocolate bars by one unit.
     * Updates inventory display across both main and management interfaces.
     *
     * @param evt The action event triggered by clicking the "KitKat Plus"
     * button
     */
    private void jButtonKitkatplsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKitkatplsActionPerformed
        mainScreen.kitkatAvb++;
        mainScreen.jTextFieldKitkatAv.setText(Integer.toString(mainScreen.kitkatAvb));
        jTextFieldKitkatAv.setText(Integer.toString(mainScreen.kitkatAvb));
    }//GEN-LAST:event_jButtonKitkatplsActionPerformed

    /**
     * Decreases the available quantity of KitKat chocolate bars by one unit,
     * with zero-value protection to prevent negative inventory.
     *
     * @param evt The action event triggered by clicking the "KitKat Minus"
     * button
     */
    private void jButtonKitkatMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKitkatMinActionPerformed
        if (mainScreen.kitkatAvb > 0) {
            mainScreen.kitkatAvb--;
        }
        mainScreen.jTextFieldKitkatAv.setText(Integer.toString(mainScreen.kitkatAvb));
        jTextFieldKitkatAv.setText(Integer.toString(mainScreen.kitkatAvb));
    }//GEN-LAST:event_jButtonKitkatMinActionPerformed

    /**
     * Increases the available quantity of Mars chocolate bars by one unit.
     * Synchronizes inventory updates between main and management interfaces.
     *
     * @param evt The action event triggered by clicking the "Mars Plus" button
     */
    private void jButtonMarsPlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMarsPlsActionPerformed
        mainScreen.marsAvb++;
        mainScreen.jTextFieldMarsAv.setText(Integer.toString(mainScreen.marsAvb));
        jTextFieldMarsAv.setText(Integer.toString(mainScreen.marsAvb));
    }//GEN-LAST:event_jButtonMarsPlsActionPerformed

    /**
     * Decreases the available quantity of Mars chocolate bars by one unit,
     * maintaining inventory integrity with zero-bound checking.
     *
     * @param evt The action event triggered by clicking the "Mars Minus" button
     */
    private void jButtonMarsMnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMarsMnActionPerformed
        if (mainScreen.marsAvb > 0) {
            mainScreen.marsAvb--;
        }
        mainScreen.jTextFieldMarsAv.setText(Integer.toString(mainScreen.marsAvb));
        jTextFieldMarsAv.setText(Integer.toString(mainScreen.marsAvb));
    }//GEN-LAST:event_jButtonMarsMnActionPerformed

    /**
     * Increases the available quantity of Kinder chocolate bars by one unit.
     * Provides real-time inventory synchronization across application
     * interfaces.
     *
     * @param evt The action event triggered by clicking the "Kinder Plus"
     * button
     */
    private void jButtonKinderPlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKinderPlsActionPerformed
        mainScreen.kinderAvb++;
        mainScreen.jTextFieldKinderAv.setText(Integer.toString(mainScreen.kinderAvb));
        jTextFieldKinderAv.setText(Integer.toString(mainScreen.kinderAvb));
    }//GEN-LAST:event_jButtonKinderPlsActionPerformed

    /**
     * Decreases the available quantity of Kinder chocolate bars by one unit,
     * ensuring inventory levels remain non-negative.
     *
     * @param evt The action event triggered by clicking the "Kinder Minus"
     * button
     */
    private void jButtonKinderMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKinderMinActionPerformed
        if (mainScreen.kinderAvb > 0) {
            mainScreen.kinderAvb--;
        }
        mainScreen.jTextFieldKinderAv.setText(Integer.toString(mainScreen.kinderAvb));
        jTextFieldKinderAv.setText(Integer.toString(mainScreen.kinderAvb));
    }//GEN-LAST:event_jButtonKinderMinActionPerformed

    /**
     * Increases the quantity of 10-cent coins by one unit. Updates both coin
     * inventory and total machine money value, with proper monetary rounding to
     * prevent floating-point errors.
     *
     * @param evt The action event triggered by clicking the "10c Plus" button
     */
    private void jButton10cPlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10cPlsActionPerformed
        mainScreen.c10Coins++;
        mainScreen.machineMoney += 0.10;
        mainScreen.machineMoney = roundMoney(mainScreen.machineMoney);
        jTextFieldMachineMoney.setText("€" + Double.toString(mainScreen.machineMoney));
        jTextField10cCoins.setText(Integer.toString(mainScreen.c10Coins));

    }//GEN-LAST:event_jButton10cPlsActionPerformed

    /**
     * Decreases the quantity of 10-cent coins by one unit. Reduces both coin
     * inventory and total machine money value, with monetary rounding for
     * accuracy.
     *
     * @param evt The action event triggered by clicking the "10c Minus" button
     */
    private void jButton10cMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10cMinActionPerformed
        mainScreen.c10Coins--;
        mainScreen.machineMoney -= 0.10;
        mainScreen.machineMoney = roundMoney(mainScreen.machineMoney);
        jTextFieldMachineMoney.setText("€" + Double.toString(mainScreen.machineMoney));
        jTextField10cCoins.setText(Integer.toString(mainScreen.c10Coins));
    }//GEN-LAST:event_jButton10cMinActionPerformed

    /**
     * Increases the quantity of 20-cent coins by one unit. Updates coin
     * inventory and recalculates total machine value.
     *
     * @param evt The action event triggered by clicking the "20c Plus" button
     */
    private void jButton20cPlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20cPlsActionPerformed
        mainScreen.c20Coins++;
        mainScreen.machineMoney += 0.20;
        mainScreen.machineMoney = roundMoney(mainScreen.machineMoney);
        jTextFieldMachineMoney.setText("€" + Double.toString(mainScreen.machineMoney));
        jTextField20cCoins.setText(Integer.toString(mainScreen.c20Coins));
    }//GEN-LAST:event_jButton20cPlsActionPerformed

    /**
     * Decreases the quantity of 20-cent coins by one unit. Adjusts both coin
     * count and total machine money value.
     *
     * @param evt The action event triggered by clicking the "20c Minus" button
     */
    private void jButton20cMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20cMinActionPerformed
        mainScreen.c20Coins--;
        mainScreen.machineMoney -= 0.20;
        mainScreen.machineMoney = roundMoney(mainScreen.machineMoney);
        jTextFieldMachineMoney.setText("€" + Double.toString(mainScreen.machineMoney));
        jTextField20cCoins.setText(Integer.toString(mainScreen.c20Coins));
    }//GEN-LAST:event_jButton20cMinActionPerformed

    /**
     * Increases the quantity of 50-cent coins by one unit. Updates inventory
     * and recalculates total machine value with proper rounding.
     *
     * @param evt The action event triggered by clicking the "50c Plus" button
     */
    private void jButton50cPlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50cPlsActionPerformed
        mainScreen.c50Coins++;
        mainScreen.machineMoney += 0.50;
        mainScreen.machineMoney = roundMoney(mainScreen.machineMoney);
        jTextFieldMachineMoney.setText("€" + Double.toString(mainScreen.machineMoney));
        jTextField50cCoins.setText(Integer.toString(mainScreen.c50Coins));
    }//GEN-LAST:event_jButton50cPlsActionPerformed

    /**
     * Decreases the quantity of 50-cent coins by one unit. Adjusts inventory
     * and updates total machine money display.
     *
     * @param evt The action event triggered by clicking the "50c Minus" button
     */
    private void jButton50cMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50cMinActionPerformed
        mainScreen.c50Coins--;
        mainScreen.machineMoney -= 0.50;
        mainScreen.machineMoney = roundMoney(mainScreen.machineMoney);
        jTextFieldMachineMoney.setText("€" + Double.toString(mainScreen.machineMoney));
        jTextField50cCoins.setText(Integer.toString(mainScreen.c50Coins));
    }//GEN-LAST:event_jButton50cMinActionPerformed

    /**
     * Increases the quantity of 1-euro coins by one unit. Updates coin
     * inventory and increases total machine money by €1.00.
     *
     * @param evt The action event triggered by clicking the "1 Euro Plus"
     * button
     */
    private void jButton1euroPlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1euroPlsActionPerformed
        mainScreen.euro1Coins++;
        mainScreen.machineMoney += 1.00;
        mainScreen.machineMoney = roundMoney(mainScreen.machineMoney);
        jTextFieldMachineMoney.setText("€" + Double.toString(mainScreen.machineMoney));
        jTextField1euroCoins.setText(Integer.toString(mainScreen.euro1Coins));
    }//GEN-LAST:event_jButton1euroPlsActionPerformed

    /**
     * Decreases the quantity of 1-euro coins by one unit. Reduces coin
     * inventory and decreases total machine money by €1.00.
     *
     * @param evt The action event triggered by clicking the "1 Euro Minus"
     * button
     */
    private void jButton1euroMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1euroMinActionPerformed
        mainScreen.euro1Coins--;
        mainScreen.machineMoney -= 1.00;
        mainScreen.machineMoney = roundMoney(mainScreen.machineMoney);
        jTextFieldMachineMoney.setText("€" + Double.toString(mainScreen.machineMoney));
        jTextField1euroCoins.setText(Integer.toString(mainScreen.euro1Coins));
    }//GEN-LAST:event_jButton1euroMinActionPerformed

    /**
     * Increases the quantity of 2-euro coins by one unit. Updates inventory and
     * increases total machine money by €2.00.
     *
     * @param evt The action event triggered by clicking the "2 Euro Plus"
     * button
     */
    private void jButton2euroPlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2euroPlsActionPerformed
        mainScreen.euro2Coins++;
        mainScreen.machineMoney += 2.00;
        mainScreen.machineMoney = roundMoney(mainScreen.machineMoney);
        jTextFieldMachineMoney.setText("€" + Double.toString(mainScreen.machineMoney));
        jTextField2euroCoins.setText(Integer.toString(mainScreen.euro2Coins));
    }//GEN-LAST:event_jButton2euroPlsActionPerformed

    /**
     * Decreases the quantity of 2-euro coins by one unit. Reduces inventory and
     * decreases total machine money by €2.00.
     *
     * @param evt The action event triggered by clicking the "2 Euro Minus"
     * button
     */
    private void jButton2euroMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2euroMinActionPerformed
        mainScreen.euro2Coins--;
        mainScreen.machineMoney -= 2.00;
        mainScreen.machineMoney = roundMoney(mainScreen.machineMoney);
        jTextFieldMachineMoney.setText("€" + Double.toString(mainScreen.machineMoney));
        jTextField2euroCoins.setText(Integer.toString(mainScreen.euro2Coins));
    }//GEN-LAST:event_jButton2euroMinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addStockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addStockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addStockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addStockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addStockFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10cMin;
    private javax.swing.JButton jButton10cPls;
    private javax.swing.JButton jButton1euroMin;
    private javax.swing.JButton jButton1euroPls;
    private javax.swing.JButton jButton20cMin;
    private javax.swing.JButton jButton20cPls;
    private javax.swing.JButton jButton2euroMin;
    private javax.swing.JButton jButton2euroPls;
    private javax.swing.JButton jButton50cMin;
    private javax.swing.JButton jButton50cPls;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonKinderMin;
    private javax.swing.JButton jButtonKinderPls;
    private javax.swing.JButton jButtonKitkatMin;
    private javax.swing.JButton jButtonKitkatpls;
    private javax.swing.JButton jButtonMarsMn;
    private javax.swing.JButton jButtonMarsPls;
    private javax.swing.JButton jButtonTwixMin;
    private javax.swing.JButton jButtonTwixPls;
    private javax.swing.JLabel jLabel10c;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel1euro;
    private javax.swing.JLabel jLabel20c;
    private javax.swing.JLabel jLabel2euro;
    private javax.swing.JLabel jLabel50c;
    private javax.swing.JLabel jLabelFloat;
    private javax.swing.JLabel jLabelKinder;
    private javax.swing.JLabel jLabelKitkat;
    private javax.swing.JLabel jLabelMars;
    private javax.swing.JLabel jLabelStock;
    private javax.swing.JLabel jLabelTwix;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField10cCoins;
    private javax.swing.JTextField jTextField1euroCoins;
    private javax.swing.JTextField jTextField20cCoins;
    private javax.swing.JTextField jTextField2euroCoins;
    private javax.swing.JTextField jTextField50cCoins;
    private javax.swing.JTextField jTextFieldErrorField;
    private javax.swing.JTextField jTextFieldKinderAv;
    private javax.swing.JTextField jTextFieldKitkatAv;
    public static javax.swing.JTextField jTextFieldMachineMoney;
    private javax.swing.JTextField jTextFieldMarsAv;
    private javax.swing.JTextField jTextFieldTwixAv;
    // End of variables declaration//GEN-END:variables
}
